name: "Recipe 13: EURUSD Market"
description: "Complete EURUSD market with IRS, cross-currency and FX volatility"

fx_rates:
  eurusd: 1.0867
  settlement: "2024-05-30"

curves:
  - id: "estr"
    interpolation: "log_linear"
    convention: "act360"
    calendar: "tgt"
    nodes:
      2024-05-28: 1.0
      2024-06-06: 1.0  # 1w
      2024-06-13: 1.0  # 2w
      2024-06-20: 1.0  # 3w
      2024-06-30: 1.0  # 1m
      2024-07-30: 1.0  # 2m
      2024-08-30: 1.0  # 3m
      2025-05-30: 1.0  # 1y
      2026-05-30: 1.0  # 2y
      2027-05-30: 1.0  # 3y
      2029-05-30: 1.0  # 5y
      2034-05-30: 1.0  # 10y

  - id: "sofr"
    interpolation: "log_linear"
    convention: "act360"
    calendar: "nyc"
    nodes:
      2024-05-28: 1.0
      2024-06-06: 1.0
      2024-06-13: 1.0
      2024-06-20: 1.0
      2024-06-30: 1.0
      2024-07-30: 1.0
      2024-08-30: 1.0
      2025-05-30: 1.0
      2026-05-30: 1.0
      2027-05-30: 1.0
      2029-05-30: 1.0
      2034-05-30: 1.0

  - id: "eurusd"
    interpolation: "log_linear"
    convention: "act360"
    calendar: "tgt"
    nodes:
      2024-05-28: 1.0
      2024-08-30: 1.0  # 3m
      2024-11-30: 1.0  # 6m
      2025-02-28: 1.0  # 9m
      2025-05-30: 1.0  # 1y
      2026-05-30: 1.0  # 2y
      2027-05-30: 1.0  # 3y
      2029-05-30: 1.0  # 5y
      2034-05-30: 1.0  # 10y

instruments:
  # EUR IRS instruments
  - type: "irs"
    effective: "2024-05-30"
    termination: "1w"
    currency: "eur"
    convention: "act360"
  - type: "irs"
    effective: "2024-05-30"
    termination: "2w"
    currency: "eur"
    convention: "act360"
  - type: "irs"
    effective: "2024-05-30"
    termination: "3w"
    currency: "eur"
    convention: "act360"
  - type: "irs"
    effective: "2024-05-30"
    termination: "1m"
    currency: "eur"
    convention: "act360"
  # ... (additional instruments)

  # Cross-currency swaps
  - type: "xcs"
    effective: "2024-05-30"
    termination: "3m"
    currency: "eur"
    leg2_currency: "usd"
    convention: "act360"
  - type: "xcs"
    effective: "2024-05-30"
    termination: "6m"
    currency: "eur"
    leg2_currency: "usd"
    convention: "act360"

solvers:
  - id: "eur_solver"
    curves: ["estr"]
    instruments: [0, 1, 2, 3]
    market_rates: [3.9035, 3.9046, 3.8271, 3.7817]

  - id: "usd_solver"
    curves: ["sofr"]
    instruments: [0, 1, 2, 3]
    market_rates: [5.3267, 5.3257, 5.3232, 5.3191]

  - id: "xcs_solver"
    curves: ["eurusd"]
    instruments: [4, 5]
    market_rates: [-2.5, -3.125]
    pre_solvers: ["eur_solver", "usd_solver"]
    fx_rates:
      eurusd: 1.0867

volatility_surface:
  expiries: ["1m", "2m", "3m", "6m", "9m", "1y", "2y"]
  delta_points:
    25d_put: [12.5, 12.8, 13.0, 13.5, 14.0, 14.2, 14.5]
    10d_put: [13.0, 13.3, 13.5, 14.0, 14.5, 14.8, 15.0]
    atm: [11.5, 11.8, 12.0, 12.5, 13.0, 13.2, 13.5]
    10d_call: [13.0, 13.3, 13.5, 14.0, 14.5, 14.8, 15.0]
    25d_call: [12.5, 12.8, 13.0, 13.5, 14.0, 14.2, 14.5]

outputs:
  - "curve_rates"
  - "npv"
  - "risk"
  - "fx_analysis"
  - "volatility_surface"

metadata:
  recipe_number: 13
  category: "FX Volatility Surface Building"
  complexity: "Advanced"